baseURL = 'http://VirtualBHP.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
[[menu.main]]

identifier = "tags"

name = "Tags"

url = "/tags/"

weight = 10